<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Nest</title>
</head>
<body>
	<header>
		<h1>Nest</h1>
	</header>

	<div id="content">
		<?php echo $content; ?>
	</div>

	<footer>
		Site generated by Nest © 2012
	</footer>
</body>
</html>